### ISSUE TITLE
pod install后的问题

### ISSUE THREAD

**Issue by ProgZXC** [QuintGao/GKDYVideo#10]
Unable to load contents of file list: '/Users/***/Downloads/GKDYVideo-master/Pods/Target Support Files/Pods-GKDYVideo/Pods-GKDYVideo-frameworks-Debug-input-files.xcfilelist' (in target 'GKDYVideo')

Unable to load contents of file list: '/Users/***/Downloads/GKDYVideo-master/Pods/Target Support Files/Pods-GKDYVideo/Pods-GKDYVideo-frameworks-Debug-output-files.xcfilelist' (in target 'GKDYVideo')

**Comment by ProgZXC** [comment]
pod --version 1.6.2
CocoaPods 1.7.0.rc.2 is available.

**Comment by QuintGao** [comment]
更新cocoapods到1.7.0就行了

**Comment by ProgZXC** [comment]
sudo gem install cocoapods 只会更新到 1.6.2 
要sudo gem install -n /usr/local/bin cocoapods -v 1.7.0这样 升级到指定版本吗？
萌新~~

**Comment by ProgZXC** [comment]
sudo gem install cocoapods --pre 这样？

**Comment by ProgZXC** [comment]
sudo gem install cocoapods --pre 
pod --version 1.7.0.rc.2
pod setup
pod install
可以了
