### ISSUE TITLE
cpu占用率一直是50%以上、  能否抽时间 检测下哪里的问题、  其他地方都很好、 有挺多可以借鉴的

### ISSUE THREAD

**Issue by EntityGJ** [QuintGao/GKDYVideo#28]
![CPU](https://user-images.githubusercontent.com/16132160/115666154-cdd9bf00-a376-11eb-86db-ee3dd33b6090.jpg)

**Comment by QuintGao** [comment]
你用的是模拟器吧，模拟器的确会这样，最好使用真机

**Comment by EntityGJ** [comment]
我 刚才用模拟器 运行你的demo  发现 CPU直接打满了 是模拟器就会有这个问题吗？  上面那个前几天给你发的图 是你的demo用真机跑的   我没试其他低版本机型 什么效果。
![image](https://user-images.githubusercontent.com/16132160/116118577-0d463980-a6f0-11eb-8fa5-ba5b77edc51e.png)
