### ISSUE TITLE
dyld[10938]: Library not loaded: '@rpath/libswiftCoreGraphics.dylib'

### ISSUE THREAD

**Issue by YangYueFan** [QuintGao/GKDYVideo#30]
项目报错dyld[10938]: Library not loaded: '@rpath/libswiftCoreGraphics.dylib'
跑不起来
<img width="1012" alt="截屏2023-06-09 18 53 05" src="https://github.com/QuintGao/GKDYVideo/assets/20474007/588c0256-788d-4807-8a17-c3a5c586cafc">

**Comment by QuintGao** [comment]
GKPageSmoothView更新到1.8.8版本
