### ISSUE TITLE
M1 mac跑不起来为啥

### ISSUE THREAD

**Issue by zengxiang21** [QuintGao/GKDYVideo#31]
<img width="1317" alt="截屏2023-07-13 23 49 23" src="https://github.com/QuintGao/GKDYVideo/assets/38372439/24a43bbb-6b20-4ea1-890c-c23f3b537ee3">

**Comment by zengxiang21** [comment]
<img width="574" alt="截屏2023-07-13 23 51 01" src="https://github.com/QuintGao/GKDYVideo/assets/38372439/832deee4-91b9-4808-b05b-8c0c899d4952">

**Comment by zengxiang21** [comment]
新手求助呜呜呜

**Comment by QuintGao** [comment]
pod install 一下
